apiVersion: v1
kind: PersistentVolume
metadata:
  name: 1312-pv
  namespace: ckad-1312
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mydata"