apiVersion: v1
kind: Pod
metadata:
  name: my-kubernetes-dashboard
spec:
  containers:
    - name: my-kubernetes-dashboard
      image: busybox
  serviceAccountName: dashboard-sa
  automountServiceAccountToken: false