apiVersion: v1
kind: Pod
metadata:
  name: ready-togo
spec:
  containers:
  - image: nginx
    name: nginx-container
    ports:
      - containerPort: 80
  - image: busybox
    name: busybox-container
    command: ['sleep', '3600']
    readinessProbe:   #проверяется порт того же самого pod-а
      tcpSocket:
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10


