apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  serviceName: mysql-h   #имя Headless Service
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Passw0rd"
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume