apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx   #имя релиза из команды "helm install hello-world-1 ./nginx-chart"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: {{ default "nginx" .Values.image.repository }}
        name: nginx
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
