apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: google-storage   #имя SC из файла sc-definition.yaml
  resources:
    requests:
      storage: 500Mi