apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold
provisioner: kubernetes.io/gce-pd
parameters:                          #специфические для каждого provisioner параметры
  type: pd-ssd
  replication-type: none