apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: silver
provisioner: kubernetes.io/gce-pd
parameters:                          #специфические для каждого provisioner параметры
  type: pd-standard
  replication-type: none