apiVersion: v1
kind: Pod
metadata:
  name: secretbox-pod
  namespace: default
spec:
  containers:
  - name: secretbox-cont
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /secretstuff
      name: secret
  volumes:
  - name: secret
    secret:
      secretName: secretstuff  #секрет уже создан ранее