apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce   #как volume должен быть смонтирован на хосте, может быть еще ReadOnlyMany, ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:         #этот тип storage не рекомендуется использовать в prod-е
    path: /tmp/data