apiVersion: v1
kind: Pod
metadata:
  name: multipod
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "300"
  - name: nginx
    image: nginx