events {}

    http {
      server {
        listen 8096;
        index index.html index.htm index.php;
        root  /var/www/html;
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    } 


---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-phpfpm
  name: nginx-phpfpm
spec:
  containers:
  - image: nginx:latest
    name: nginx-container
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: shared-files
      mountPath: /var/www/html
  - image: php:8.2-fpm-alpine
    name: php-fpm-container
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html
  volumes:
  - name: shared-files
    emptyDir: {}
  - name: nginx-config-volume
    configMap:
      name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - port: 8098
    protocol: TCP
    targetPort: 8098
    nodePort: 30012
  selector:
    app: nginx-phpfpm
  type: NodePort