apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: nautilus
spec:
  containers:
  - image: busybox:latest
    name: time-check
    command: [ "/bin/sh", "-c" ]
    args: [ "while true; do date; sleep $TIME_FREQ;done > /opt/security/time/time-check.log" ]
    env:
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
    volumeMounts:
    - name: log-volume
      mountPath: /opt/security/time
  volumes:
  - name: log-volume
    emptyDir: {}