apiVersion: v1
kind: Pod
metadata:
  name: lab-pv-pod
spec:
  volumes:
    - name: pvlab
      persistentVolumeClaim:
        claimName: lab-pv-claim
  containers:
  - name: lab-container
    image: httpd
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: "/var/www/html"
        name: pvlab

