apiVersion: v1
kind: Pod
metadata:
  name: lab-pv-pod
spec:
  volumes:
    - name: pvlab   #рандомное придуманное имя, не ссылка на реально созданный pv
      persistentVolumeClaim:
        claimName: lab-pv-claim   #имя claim из файла lab-pvc.yaml
  containers:
  - name: lab-container
    image: httpd
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: "/var/www/html"
        name: pvlab   #имя volume из секции выше

