apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: "{{ .Values.image.repository }}"
        name: nginx
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
