apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Passw0rd"
  serviceName: mysql-h
  podManagementPolicy: Parallel      #переопределить стандартное поведение StatefulSet - последовательный запуск pod-ов одного за другим, и вместо этого запускать их параллельно