apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  #namespace: finance   #также можно указать определенный namespace
rules:
- apiGroups: [""]   #для Core Group можно оставить пустым, для остальных нужно указывать Group Name
  resources: ["pods"]
  verbs: ["list", "get", "create", "update", "delete"]
  #resourceNames: ["blue", "orange"]   #также можно дать доступ только к определенным pod-ам
- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["create"]