apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:   #какие типы ресурсов шифровать
      - secrets
    providers:   #какими провайдерами шифровать
      - aescbc:  #здесь имеет значение порядок провайдеров, если например первый identity, то шифрование выполняться не будет
          keys:
            - name: key1
              secret: A9l0+oFroiRCcErGVpciQRg4n2rWqBX+CqyEw1CRg1I=   #из команды "head -c 32 /dev/urandom | base64"
      - identity: {}   #вообще без шифрования