apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret   #имя секрета из файла secret-data.yaml
#      env:
#        - name: DB_Password   #имя environment variable в приложении
#          valueFrom:
#            secretKeyRef:     #вставить только одну определенную key/value пару из Secret
#              name: app-secret
#              key: DB_Password    #имя environment variable в Secret
#      volumes:
#      - name: app-secret-volume
#        secret:
#          secretName: app-secret     #вставить как volume